### ISSUE TITLE
target is defined in xar-assembly.xml

### ISSUE THREAD

**Issue by line-o** [nverwer/eXist-components#2]
in xar-assembly.xml the <target>-element is set

https://github.com/nverwer/svg-qr/blob/e9dfb6d5b6b70dc44cbf3cb9e5d2430e6faab7db/xar-assembly.xml#L22

this makes the resulting XAR a ressource-package instead of a pure library. Those are installed in the collection `/db/system/repo/`, like functx for example.

I do not know if this intentional, but if it isn't then it might be worth trying to build without a target set.

**Comment by nverwer** [comment]
I have made the xar-assembly by copy-pasting, not knowing what I am doing.
The project does contain resources, and my assumption was that the target element is needed to copy those resources.
I will try removing the target element.

**Comment by nverwer** [comment]
This seems to work.
